# This file relates to internal XMOS infrastructure and should be ignored by users

an_number: AN0xxxx
project: '{{an_number}}'
title: '{{an_number}}: app_note_title'
version: 1.0.0

documentation:
  exclude_patterns_path: doc/exclude-patterns.inc
  root_doc: doc/rst/an0xxxx.rst
  cognidox_part_number: XM-000000-AN
  pdfs:
    doc/rst/an0xxxx.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{an_number}}_v{{version}}'
      pdf_short: yes
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{an_number}}_v{{version}}_readme'
      pdf_short: yes

software:
  cognidox_part_number: XM-000000-SM

